name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
      - run: vp check
      - run: vp test
      - run: vp run typedoc
      - uses: actions/upload-artifact@v4
        with:
          name: typedoc-json
          path: typedoc.json

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
      - uses: dtinth/setup-playwright-test-docker@main
      - run: vp exec playwright test
